version: '3.8'

services:
  flask:
    build: .
    container_name: flask
    volumes:
      - ../app:/app
    expose:
      - "5000"
    restart: always
    env_file:
      - .env
    command: >
      python3 app.py
    networks:
      - pass-app-net

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    restart: always
    ports:
      - "443:443"
      - "80:80" 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/ssl:/etc/ssl/
      - ../nginx/www:/var/www/html
    networks:
      - pass-app-net
networks:
  pass-app-net: